### ISSUE TITLE
How to handle StartLambdaFunctionFailed error, using promises?

### ISSUE THREAD

**Issue by fkshiomi** [aws/aws-swf-build-tools#5]
I have been using AWS SWF to coordinate [lambda tasks](http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/lambda-task.html). I'm using [SWF Error Handling](http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/errorhandling.html) + [SWF Promises](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/flow/core/Promise.html) + [Replay Behavior](http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/programming-replay.html#programming-replay-asynchronous) of AWS SWF Java SDK.

SWF Lambda Task + SWF Promise + SWF TryCatch are powerful features, because when Lambda function throws an exception "SWF TryCatch" gives me a way to handle the errors. It works very well!!

Here we have example:

> 
> 1       new TryCatch() {
> 2
> 3       @Override
> 4       protected void doTry() throws Throwable {
> 5         Promise<String> promiseLambda =  lambdaClient.scheduleLambdaFunction("transcodeSegment_mock", "");
> 6         
> 7         finishedWorkflow(promiseLambda);
> 8       }
> 9 
>10       @Override
>11       protected void doCatch(
>12           Throwable e
>13       ) throws Throwable {
>14         System.out.println("doCatch *** Error handling routine");
>15         System.out.println(e.getMessage());
>16         .... error handle code
>17       }
>18     };

  But, I saw a diferente behavior, when SWF has Event Type="StartLambdaFunctionFailed" or Event Type="ScheduleLambdaFunctionFailed", for both cases Catch statement (line 11) is not being called.
  Is it normal? How can I handle those types of SWF Events, using only promises? 
  As you can see in my code, it does not parse Workflow History, I'm using just promises and Replay Behavior. Is possible to handle those errors, without my code parse workflow history?

  When Event Type="StartLambdaFunctionFailed" or Event Type="ScheduleLambdaFunctionFailed" happens, workflow never finishes, and I have timeout error.

  Thanks

**Comment by Jianchu** [comment]
The fix for this is introduced through commit: https://github.com/aws/aws-swf-flow-library/commit/98bfa83cb66da0e9ec08f4dd43ee2b7977f06368
Please look at code in AysncDecider for details: https://github.com/aws/aws-swf-flow-library/blame/master/src/main/java/com/amazonaws/services/simpleworkflow/flow/worker/AsyncDecider.java#L314-L319
